### ISSUE TITLE
Remove annotator artefacts from extraction repo.

### ISSUE THREAD

**Issue by sdsen** [eBPFDevSecTools/opened_extraction#82]
We are going to do further annotation work here: https://github.com/eBPFDevSecTools/ebpf-projects-annotations

**Comment by sdsen** [comment]
removed the code and asset files and modified dockerfile.
@palanik1 can you remove the commented_* files and other generated artefacts once they have been moved to new repo?

**Comment by palanik1** [comment]
Closing as done.
